---
title: "Exploring Weather Trends in Elmira, NY from 1981 - 2010"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)

library(tidyverse)
library(plotly)
library(p8105.datasets)

data("ny_noaa")

ny_noaa_elmira = ny_noaa |>
  filter(id == 'USC00302610') |> 
  mutate(tmin = (as.numeric(tmin)/10)*(9/5) + 32) |> 
  mutate(tmax = (as.numeric(tmax)/10)*(9/5) + 32) |> 
  mutate(month = str_sub(as.character(date),start = 6, end = 7)) |> 
  mutate(day = str_sub(as.character(date), start = 9, end = 10)) |> 
  mutate(year = str_sub(as.character(date), start = 1, end = 4))

ny_noaa_elmira

```

Column {data-width=650}
-----------------------------------------------------------------------

### Octobrrrr: Minimum Observed Temperatures (F) on Halloween in Elmira, NY

```{r}
ny_noaa_elmira |> 
  filter(month == '10' & day == '31') |> 
  plot_ly(x = ~year, y = ~tmin, color = ~tmin, type = "bar", colors = 'viridis')
  
```

Column {data-width=350}
-----------------------------------------------------------------------

### Average Max Temperature (F) by Month and Year

```{r}
ny_noaa_elmira |> 
  group_by(month, year) |>
  mutate(monthly_max_avg = mean(tmax)) |> 
  plot_ly(x = ~month, y = ~monthly_max_avg, color = ~year, type = 'scatter', mode = 'markers', colors = "viridis", alpha = 0.5)
```

### Average Min Temperature (F) by Month

```{r}
ny_noaa_elmira |> 
  group_by(month) |>
  plot_ly(x = ~month, y = ~tmin, type = 'box')
```

